/*
	version: 1.1.3
	fecha: 03-04-2020
*/

create or replace PACKAGE PKG_CONSULTAS_CANONICO AS 

--PROCEDIMIENTOS COMUNES
PROCEDURE PRC_GET_CONTACTOS_ENTIDAD_FULL(P_RUT_CONTACTO IN VARCHAR, P_ID_ENTIDAD IN VARCHAR, P_ENTIDAD IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_DIRECCION_ENTIDAD(P_ID_ENTIDAD IN VARCHAR, P_ENTIDAD IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_DIRECCION_FULL(P_ID_ENTIDAD IN VARCHAR, P_ENTIDAD IN VARCHAR, P_TIPO_CLIENTE IN VARCHAR, P_RESP OUT SYS_REFCURSOR);

--PROCEDIMIENTOS DE LA CADENA
PROCEDURE PRC_GET_CADENA_FULL(P_ID_CADENA IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_LOCALES_CADENA_FULL(P_ID_CADENA IN VARCHAR, P_RESP OUT SYS_REFCURSOR);

--PROCEDIMIENTOS DEL CONTACTO
PROCEDURE PRC_GET_CONTACTOS_FULL(P_RUT_CONTACTO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_MEDIO_CONTACTO_FULL(P_ID_CONTACTO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);

--PROCEDIMIENTO DEL LOCAL
PROCEDURE PRC_GET_LOCAL_FULL(P_ID_LOCAL IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_PTO_VTA_LOCAL_LOV(P_ID_LOCAL IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_MEDIO_CONTACTO_LOCAL_FULL(P_ID_LOCAL IN VARCHAR, P_RESP OUT SYS_REFCURSOR);

--PROCEDIMIENTOS DEL PUNTO_VENTA
PROCEDURE PRC_GET_PTO_VTA_FULL(P_ID_PTO_VTA IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_RUBRO_PTO_VTA_FULL(P_ID_PTO_VTA IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_ATRIBUTOS_PRODUCTO_PTO_VTA_FULL(P_ID_PTO_VTA IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_MEDIO_PAGO_MARCA_PTO_VTA_FULL(P_ID_PTO_VTA IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_PRODUCTOS_CONTRATADOS_PTO_VTA_FULL(P_ID_PTO_VTA IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_PRODUCTOS_FINANCIEROS_PTO_VTA_FULL(P_ID_PTO_VTA IN VARCHAR, P_ID_PROD_CANAL IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_PRODUCTOS_FINANCIEROS_FULL(P_ID_PROD_CANAL IN VARCHAR, P_RESP OUT SYS_REFCURSOR);

--PROCEDIMIENTOS DEL CLIENTE
PROCEDURE PRC_GET_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_TIPO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_CLIENTE_RELACION_LOV(P_ID_CLIENTE IN VARCHAR, P_TIPO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_CONTACTOS_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_TIPO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_CADENA_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_MEDIO_CONTACTO_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_TIPO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_LOCAL_CLIENTE_LOV(P_RUT_CLIENTE IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_LOCAL_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_RUBRO_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_TIPO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_CTA_ABONO_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_MEDIO_PAGO_MARCA_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_TIPO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_PROD_CONTRATADOS_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_TIPO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_PROD_FINANCIEROS_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_ID_PROD_CANAL IN VARCHAR, P_TIPO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_ATRIBUTOS_PRODUCTO_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_TIPO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_COMERCIO_SECUNDARIO_CLIENTE_LOV(P_RUT_CLIENTE IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_COMERCIO_SECUNDARIO_CLIENTE_FULL(P_RUT_CLIENTE IN VARCHAR, P_RESP OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_PROD_ASOC_FULL(P_ID_COMERCIO_SECUNDARIO IN VARCHAR, P_RESP OUT SYS_REFCURSOR);

END PKG_CONSULTAS_CANONICO;